"""
SHERLOCK — Sprint D5: UI localization backend support.

The frontend rewrite is Stage G — this module does NOT touch any
frontend file. It only exposes static, versionable string bundles the
(future) frontend can fetch via `GET /language/resources/{lang}` so
labels aren't hardcoded in either the frontend or scattered across
backend f-strings.

These are UI *chrome* strings (menu labels, static workflow copy,
discussion-panel headers) — not investigation content. Investigation
content (queries, findings, narratives, activity-feed messages) is
translated live by `TranslationService`, because it's unbounded,
dynamic text; these resource bundles are the small, fixed vocabulary
around it, translated once and shipped as data.

Adding a language (Sprint D6): add a new top-level key here (e.g.
"hi", "ta", "te") with the same key structure as "en"/"kn". No code
change needed — `get_resources` and the API route are already
language-agnostic. `SUPPORTED_LANGUAGES` is the one place that gates
what `TranslationService`/`language_detector` actively support; a
resource bundle can exist ahead of full translation-engine support for
that language, or vice versa — the two are intentionally decoupled.
"""

from __future__ import annotations

SUPPORTED_LANGUAGES = ("en", "kn")

RESOURCES = {
    "en": {
        "labels": {
            "app_name": "SHERLOCK",
            "app_tagline": "Crime Intelligence Platform",
            "new_investigation": "New Investigation",
            "activity_feed": "Activity Feed",
            "investigation_board": "Investigation Board",
            "final_report": "Final Report",
            "export_pdf": "Export PDF",
            "settings": "Settings",
        },
        "activity": {
            "investigation_started": "Investigation started",
            "agent_completed": "completed",
            "agent_skipped": "skipped",
            "agent_failed": "failed",
            "report_ready": "Investigation complete. Final report ready.",
            "clarification_needed": "Clarification needed",
            "topic_reset": "Context reset",
            "query_translated": "Query translated for processing",
        },
        "workflow": {
            "ask_a_question": "Ask a question about a case, person, or pattern...",
            "submit": "Submit",
            "listening": "Listening...",
            "processing": "Processing...",
        },
        "discussion": {
            "discussion_started": "Reviewing specialist findings for agreement/disagreement...",
            "opinion": "Opinion",
            "disagreement": "Disagreement",
            "consensus": "Consensus",
            "confidence": "Confidence",
        },
        "pdf": {
            "case_id": "CASE ID",
            "generated": "GENERATED",
            "status": "STATUS",
            "classified": "CLASSIFIED",
            "investigation_query": "INVESTIGATION QUERY",
            "original_query": "ORIGINAL QUERY",
            "summary": "SUMMARY",
            "timeline": "INVESTIGATION TIMELINE",
            "reasoning_path": "REASONING PATH",
            "key_findings": "KEY FINDINGS",
            "validated": "validated",
            "confidence_heatmap": "CONFIDENCE HEATMAP",
            "recommended_actions": "RECOMMENDED ACTIONS",
            "footer": "Generated by SHERLOCK Crime Intelligence Platform",
            "official_use_only": "FOR OFFICIAL USE ONLY",
            "high": "HIGH", "medium": "MEDIUM", "low": "LOW",
            "finding_col": "Finding", "agent_col": "Agent",
            "confidence_col": "Confidence", "status_col": "Status",
            "translation_notice": "This report was machine-translated from English. "
                                   "It is an investigative aid, not a certified legal translation.",
            "font_fallback_notice": "Kannada font unavailable on this server; report rendered in English.",
        },
    },
    "kn": {
        "labels": {
            "app_name": "ಶೆರ್ಲಾಕ್",
            "app_tagline": "ಅಪರಾಧ ಗುಪ್ತಚರ ವೇದಿಕೆ",
            "new_investigation": "ಹೊಸ ತನಿಖೆ",
            "activity_feed": "ಚಟುವಟಿಕೆ ಫೀಡ್",
            "investigation_board": "ತನಿಖಾ ಫಲಕ",
            "final_report": "ಅಂತಿಮ ವರದಿ",
            "export_pdf": "PDF ರಫ್ತು ಮಾಡಿ",
            "settings": "ಸೆಟ್ಟಿಂಗ್\u200cಗಳು",
        },
        "activity": {
            "investigation_started": "ತನಿಖೆ ಪ್ರಾರಂಭವಾಗಿದೆ",
            "agent_completed": "ಪೂರ್ಣಗೊಂಡಿದೆ",
            "agent_skipped": "ಬಿಟ್ಟುಬಿಡಲಾಗಿದೆ",
            "agent_failed": "ವಿಫಲವಾಗಿದೆ",
            "report_ready": "ತನಿಖೆ ಪೂರ್ಣಗೊಂಡಿದೆ. ಅಂತಿಮ ವರದಿ ಸಿದ್ಧವಾಗಿದೆ.",
            "clarification_needed": "ಸ್ಪಷ್ಟೀಕರಣ ಅಗತ್ಯವಿದೆ",
            "topic_reset": "ಸಂದರ್ಭ ಮರುಹೊಂದಿಸಲಾಗಿದೆ",
            "query_translated": "ಪ್ರಕ್ರಿಯೆಗಾಗಿ ಪ್ರಶ್ನೆಯನ್ನು ಅನುವಾದಿಸಲಾಗಿದೆ",
        },
        "workflow": {
            "ask_a_question": "ಪ್ರಕರಣ, ವ್ಯಕ್ತಿ ಅಥವಾ ಮಾದರಿಯ ಬಗ್ಗೆ ಪ್ರಶ್ನೆ ಕೇಳಿ...",
            "submit": "ಸಲ್ಲಿಸಿ",
            "listening": "ಆಲಿಸಲಾಗುತ್ತಿದೆ...",
            "processing": "ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
        },
        "discussion": {
            "discussion_started": "ಒಪ್ಪಿಗೆ/ಭಿನ್ನಾಭಿಪ್ರಾಯಕ್ಕಾಗಿ ತಜ್ಞರ ಅಭಿಪ್ರಾಯಗಳನ್ನು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
            "opinion": "ಅಭಿಪ್ರಾಯ",
            "disagreement": "ಭಿನ್ನಾಭಿಪ್ರಾಯ",
            "consensus": "ಒಮ್ಮತ",
            "confidence": "ವಿಶ್ವಾಸಾರ್ಹತೆ",
        },
        "pdf": {
            "case_id": "ಪ್ರಕರಣ ಸಂಖ್ಯೆ",
            "generated": "ರಚಿಸಲಾಗಿದೆ",
            "status": "ಸ್ಥಿತಿ",
            "classified": "ವರ್ಗೀಕೃತ",
            "investigation_query": "ತನಿಖಾ ಪ್ರಶ್ನೆ",
            "original_query": "ಮೂಲ ಪ್ರಶ್ನೆ",
            "summary": "ಸಾರಾಂಶ",
            "timeline": "ತನಿಖಾ ಕಾಲಾನುಕ್ರಮ",
            "reasoning_path": "ತಾರ್ಕಿಕ ಮಾರ್ಗ",
            "key_findings": "ಪ್ರಮುಖ ಸಂಶೋಧನೆಗಳು",
            "validated": "ಮೌಲ್ಯೀಕರಿಸಲಾಗಿದೆ",
            "confidence_heatmap": "ವಿಶ್ವಾಸಾರ್ಹತೆ ಶಾಖ ನಕ್ಷೆ",
            "recommended_actions": "ಶಿಫಾರಸು ಮಾಡಿದ ಕ್ರಮಗಳು",
            "footer": "ಶೆರ್ಲಾಕ್ ಅಪರಾಧ ಗುಪ್ತಚರ ವೇದಿಕೆಯಿಂದ ರಚಿಸಲಾಗಿದೆ",
            "official_use_only": "ಅಧಿಕೃತ ಬಳಕೆಗೆ ಮಾತ್ರ",
            "high": "ಹೆಚ್ಚು", "medium": "ಮಧ್ಯಮ", "low": "ಕಡಿಮೆ",
            "finding_col": "ಸಂಶೋಧನೆ", "agent_col": "ಏಜೆಂಟ್",
            "confidence_col": "ವಿಶ್ವಾಸಾರ್ಹತೆ", "status_col": "ಸ್ಥಿತಿ",
            "translation_notice": "ಈ ವರದಿಯನ್ನು ಇಂಗ್ಲಿಷ್\u200cನಿಂದ ಯಂತ್ರ-ಅನುವಾದ ಮಾಡಲಾಗಿದೆ. "
                                   "ಇದು ತನಿಖಾ ಸಹಾಯಕವಾಗಿದೆ, ಪ್ರಮಾಣೀಕೃತ ಕಾನೂನು ಅನುವಾದವಲ್ಲ.",
            "font_fallback_notice": "ಈ ಸರ್ವರ್\u200cನಲ್ಲಿ ಕನ್ನಡ ಫಾಂಟ್ ಲಭ್ಯವಿಲ್ಲ; ವರದಿಯನ್ನು ಇಂಗ್ಲಿಷ್\u200cನಲ್ಲಿ ರಚಿಸಲಾಗಿದೆ.",
        },
    },
}

# Sprint D3 hook: localized voice-command dictionary, centralized here
# rather than in the (not-yet-built) frontend, per the handover
# ("Do not hardcode inside frontend. Keep centralized."). Command *keys*
# are canonical/English — this is what `voice/command_router.py` already
# matches against — the value per language is what the user is expected
# to say. Wiring actual Kannada ASR grammar/matching into
# `command_router.py` is Sprint D3 work and is NOT done yet; see the
# Stage D report's "Not Implemented" section.
VOICE_COMMANDS = {
    "open_investigation": {"en": "Open investigation", "kn": "ತನಿಖೆ ತೆರೆಯಿರಿ"},
    "close_case": {"en": "Close this case", "kn": "ಈ ಪ್ರಕರಣವನ್ನು ಮುಚ್ಚಿ"},
    "show_findings": {"en": "Show findings", "kn": "ಸಂಶೋಧನೆಗಳನ್ನು ತೋರಿಸಿ"},
    "read_report": {"en": "Read the report", "kn": "ವರದಿಯನ್ನು ಓದಿ"},
}


def get_resources(language: str) -> dict:
    if language not in RESOURCES:
        raise ValueError(f"Unsupported language '{language}'. Supported: {list(RESOURCES.keys())}")
    return RESOURCES[language]
